baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Jim Kalafut"

# RSS, categories and tags disabled for an easy start
# See configuration options for more details: 
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["taxonomy", "taxonomyTerm"]
theme="hugo-coder-custom"

[params]
colorScheme = "auto"
author = "Jim Kalafut"
favicon_16 = "/img/favicon-16x16.png"
favicon_32 = "/img/favicon-32x32.png"
touchIcon ="/img/apple-touch-icon.png"

[[menu.main]]
name = "About"
url = "/page/about"
weight = 1

[[menu.main]]
name = "Blogs"
url = "/page/blogs"
weight = 2

[[menu.main]]
name = "Kit"
url = "/page/kit"
weight = 3

# [[menu.main]]
# name = "Family Tree"
# url = "/page/tree-invite"
# weight = 4

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github"
  weight = 1
  url = "https://github.com/kalafut/"
[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-linkedin"
  weight = 3
  url = "https://www.linkedin.com/in/kalafut/"

[[params.social]]
  name = "Email"
  icon = "fa fa-envelope"
  weight = 3
  url = "mailto:jim@kalafut.net"

[params.goatCounter]
  code = "kalafut-blog"
